### ISSUE TITLE
Make colors used configurable

### ISSUE THREAD

**Issue by brunal** [sampsyo/beets#1238]
A [recent message on the mailing list](https://groups.google.com/forum/#!topic/beets-users/yWq6s16x4O4) asked how to modify the colors used by beets when "color: True" is set in the config. It is not currently possible, would it be worth the work? And then how would it be implemented?

An enum with COLOR1, COLOR2, etc.? Or a description of when it is used? e.g. DIFF, DIFF_MINOR, SHORTCUT, SHORTCUT_DEFAULT, PENALTY, INFO, ...

**Comment by sampsyo** [comment]
Yes, I suppose this would work by making a new configurable dict mapping roles to color names. It seems doable, but it's not quite clear how much of a problem this is (or, where it is a problem, when we should just make our default colors better :smiley:). Opinions either way would be welcome.

**Comment by tomjaspers** [comment]
It doesn't really add any overhead, and it's easy to add, so I don't see why not. The following dict can map all the color requirements that I could find (and would allow the distinction between error messages and highlights, both of which are currently *red*).

```python
COLORS = {
    'text-success': 'green',
    'text-warning': 'yellow',
    'text-error': 'red',
    'text-highlight': 'red',
    'text-highlight-minor': 'lightgray',
    'action-primary': 'turquoise',
    'action-secondary': 'blue',
}
```

I could make a PR for this, if the color names are alright

**Comment by tomjaspers** [comment]
Also see https://github.com/sampsyo/beets/issues/363, so it's not the first time this has been asked.

**Comment by brunal** [comment]
Good catch on the previous issue. Names seem fine and it seems to cover all current usages (in `beets.ui.commands` `beets.ui` `beetsplug.fetchart` and `beetsplug.play`).

`action_*` colors name could be improved, maybe `action_default` and `action_others` (or just `action`)?

Finally I prefer the named which dashes (as you initially wrote them) but that 100% personal taste.

**Comment by tomjaspers** [comment]
The whole codebase (and the config file) uses underscores, that's why I changed them from the dashes.

I agree that `action_default` fits better than *primary*. Not too sure about `action_others` though. 

I would also propose to nest the `colors` option under the `ui` config. Would be nice to have `color` there as well, but suppose that would break compatibility.

```yaml
color: yes
ui:
    terminal_width: 80
    length_diff_thresh: 10.0
    colors:
        text_success: green
        text_warning: yellow
        text_error: red
        text_highlight: red
        text_highlight_minor: lightgray
        action_default: turquoise
        action: blue
```
