### ISSUE TITLE
Impossible cancel "beet embedart"

### ISSUE THREAD

**Issue by simonbcn** [sampsyo/beets#1283]
When I press `CTRL`+`C` after execute "beet embedart", the execution isn't interrupted.

**Comment by sampsyo** [comment]
Hi there—I can't reproduce that here (control-C works fine). Can you provide details about your setup?

**Comment by simonbcn** [comment]
I execute `beet embedart` and I press `CTRL`+`C` several times but the execution continues:

![Screenshot of my terminal ](https://cloud.githubusercontent.com/assets/428231/5982639/59346414-a8c5-11e4-8bf6-9228ceeed0dc.jpg)

**Comment by sampsyo** [comment]
It's not that I didn't believe you :smiley:; I just need more details about your system.

* beets version
* Python version
* OS
* beets configuration
* imaging backend: PIL or ImageMagick?
* ...

Also, does this go away if you disable resizing?

**Comment by simonbcn** [comment]
beet git version 
Python 2.7.8
Ubuntu Trusty 64 bits

Config file:
```
directory: "/home/simon/M\xFAsica/"
library: /home/simon/.beets/musiclibrary.blb
#threaded: no
color: yes
plugins: convert chroma replaygain fetchart lastgenre scrub embedart discogs web duplicates info
#art_filename: cover

fetchart:
   maxwidth: 300
   cover_names: front folder cover 

embedart:
   maxwidth: 300

match:
    strong_rec_thresh: 0.30
    max_rec:
        missing_tracks: strong
    
import:
   art: yes
   languages: es en

paths:
   default: $albumartist/$album/$track - $title
   singleton: $artist - $title
   comp: Varios/$album/$track - $title

replaygain:
   backend: gstreamer
   auto: yes
#   backend: command
   overwrite: yes
#   apply: yes

lastgenre:
   canonical: ''
   fallback: ''
   multiple: yes
   force: no
   
convert:
   auto: yes
   command: ffmpeg -i $source -y -codec:a libmp3lame -vn -qscale:a 1 $dest
   extension: mp3
   max_bitrate: 250
   embed: yes
   quiet: yes
   
duplicates:
   path: yes
#   checksum: yes
```

The imaging backend? I don't know.
