### ISSUE TITLE
beet play: output from CLI music player not displaying

### ISSUE THREAD

**Issue by srccon** [sampsyo/beets#1321]
This is probably my CLI ignorance. I want to use mplayer with `beet play`. 

In my config files has these lines (Debian):

    play:
        command: "/usr/bin/mplayer -playlist"

The issue is that mplayer display does not show up in the terminal window, although the music does begin to play, ex: `beet play beatles`. It's just a blank terminal display.

If I spawn another terminal it works fine, but that is not what I want to do, I want to use the same terminal for CLI output from mplayer. 

    play:
        command: "terminator -x /usr/bin/mplayer -playlist"

How would I get mplayer to display in the window where invoked the `beet play` command?

Love the program, I finally feel I have control over my unwieldy music library (no thanks to itunes...).

**Comment by sampsyo** [comment]
Thanks for the report! To check whether this might be related to mplayer itself, can you try changing the command to a dummy value temporarily? For example, just `command: "echo"` should print the filenames.

**Comment by srccon** [comment]
It does the same for cvlc and nvlc. 

When I run it with `command: "echo"` it outputs `Playing 2 tracks` the returns control. 

Here is the version info

    beets version 1.3.10
    plugins: embedart, lastgenre, chroma, duplicates, play, fetchart, fromfilename, info

Current Config File:

```
directory: /media/TRAVELER/music-clean
library: /media/TRAVELER/musiclibrary.blb

import: 
    move: yes
    copy: no
    log: /media/TRAVELER/beetslog.txt

plugins: chroma duplicates play embedart fetchart fromfilename lastgenre info

play:
    command: "terminator -x /usr/bin/mplayer -shuffle -playlist"
```

Thanks so much for your help! My favorite command is `rm`, get rid of all this perfectly tagged junk music.
