### ISSUE TITLE
Beets doesn't seem to be rewriting my tags

### ISSUE THREAD

**Issue by dprus** [sampsyo/beets#1362]
Hi,

Every time I run: beet import /mnt/nas/music I see a bunch of entries like:
```
/mnt/nas/music/Aerosmith/O, Yeah! Ultimate Aerosmith Hits [2002]/AAC (30 items)
Tagging:
    Aerosmith - O, Yeah! Ultimate Aerosmith Hits
URL:
    http://musicbrainz.org/release/7fb9d2db-bf96-45bf-b089-496fe2758c20
(Similarity: 99.2%) (tracks) (2xSACD, 2002, US, Columbia)
SACD 1
 * What It Takes -> What It Takes (id)
SACD 2
This album is already in the library!
Old: 30 items, FLAC, 1017kbps, 132:16
New: 30 items, AAC, 218kbps, 132:18
[S]kip new, Keep both, Remove old? k
```
Beets shows a difference between the IDs and after I select 'k' (Keep Both) my assumption is that Beets would update the id tag of the 99.2% match to be a 100% match (i.e. fix the mismatch in the id) during the import process. However, this does not happen since if I run the beets import command again I will get the exact same prompt.

My current Beets config is as follows:
```
library: /mnt/nas/music/.beets/library.db
directory: /mnt/nas/music
plugins: fetchart embedart convert chroma info scrub lastgenre
import:
    move: yes
paths:
    default: $albumartist/$album [$year]/$format/$artist - $track - $title
    singleton: Non-Album/$artist/$format/$artist - $title
    comp: Compilations/$album [$year]/$format/$artist - $track - $title
convert:
#    auto: yes
    dest: /mnt/nas/music
    paths:
        default: $albumartist/$album [$year]/AAC/$artist - $track - $title
        singleton: Non-Album/$artist/AAC/$artist - $title
        comp: Compilations/$album [$year]/AAC/$artist - $track - $title
    never_convert_lossy_files: true
    format: aac
    formats:
        aac:
            command: ffmpeg -i $source -y -codec:a libfdk_aac -vbr 5 $dest
            extension: m4a
        mp3:
            command: ffmpeg -i $source -codec:a libmp3lame -q:a 2 $dest
            extension: mp3
#chroma:
#    auto: no
scrub:
    auto: no
```
Note that I have the "scrub" plug-in enabled and I ran a manual "beet scrub album:'ultimate aerosmith' format:'aac'" before the import to no avail.
