### ISSUE TITLE
convert: auto convert during import hangs indefinitely

### ISSUE THREAD

**Issue by autochthe** [sampsyo/beets#1381]
Auto converting files during import hangs indefinitely.

`config.yaml`
```
directory: /media/raid/beets

import:
  incremental: yes

paths:
  default: $albumartist/$album%aunique{}/$track - $title
  singleton: Non-Album/$artist/$title
  albumtype:soundtrack: Soundtracks/$album/$track - $title
  comp: Compilations/$album%aunique{}/$track - $title

plugins: web ihate scrub lastgenre fetchart embedart convert

ihate:
  skip:
    - format:mp3
    - format:alac
    - format:aac
    - format:opus
    - format:ogg
    - format:wma

lastgenre:
  canonical: yes

embedart:
  ifempty: yes

convert:
  auto: true
  command: avconv -i $source -codec:a libmp3lame -qscale:a 0 $dest
  extension: mp3
```

beet import output:
```
pi@persephone ~ $ beet import /media/raid/rip/Sia\ -\ Colour\ The\ Small\ One\ \(2004\)\/

/media/raid/rip/Sia - Colour The Small One (2004) (12 items)
Correcting tags from:
    Sia - Colour The Small One
To: 
    Sia - Colour the Small One
URL:
    http://musicbrainz.org/release/0902b776-dadf-4fce-93f2-7815acb17b3a
(Similarity: 100.0%) (CD, 2004, GB)
 * Don't Bring Me Down                -> Don’t Bring Me Down
 * Natale's Song                      -> Natale’s Song
 * The Church Of What's Happening Now -> The Church of What’s Happening Now
Encoding /media/raid/rip/Sia - Colour The Small One (2004)/08 - Butterflies.flac
```
The process hangs here

`ps aux` shows:
```
pi       21832  0.5  2.6  37616 11620 pts/2    S+   15:32   0:00 avconv -i /media/raid/rip/Sia - Colour The Small One (2004)/01 - Rewrite.flac -codec:a libmp3lame -qscale:a 0 /tmp/tmpkBxkt_.mp3
```

So the command is definitely running; however, `ls -lh /tmp` shows:
```
-rw------- 1 pi       pi       0 Mar 26 15:32 tmpkBxkt_.mp3
```
ie. nothing is being written to the file

To test whether `avconv` was at fault, I tried running the exact command shown in `ps`, but it completed successfully.  Note that `avconv` is the successor to `ffmpeg`, so their behavior should be more or less identical.

Tested using beets version 1.3.10 on Raspberry Pi B+ running Raspbian GNU/Linux 7 (wheezy) 3.18.7+
