### ISSUE TITLE
[bug] Global Option | ignore | doesn't prevent files to be moved

### ISSUE THREAD

**Issue by fohrums** [sampsyo/beets#1399]
Config
=

Specifically take look at line 7, `ignore: .jpg`
```
library: C:\Users\user\AppData\Roaming\beets\library.db
directory: d:\music
import:
    move: yes
    write: yes
    log: beetslog.txt
ignore: .jpg
plugins: discogs embedart fetchart scrub
pluginpath: c:\Python27\Lib\site-packages

paths:
    default: $albumartist/$album/$disc-$track $title
    album:_clip: _clip/$artist - $title
    album:_track: _track/$artist - $title
    album:_unofficial: _unofficial/$artist - $title
    album:_forthcoming: _forthcoming/$artist - $title
```

Environment
=
To ensure that `beets` is working properly:
```
user@home /cygdrive/d/download
$ beet version
beets version 1.3.11
plugins: discogs, embedart, fetchart, scrub
```
The directory to be imported (keep note of the soon-to-be ignored file, <b>cover.jpg</b>):
```
user@home /cygdrive/d/download/While You Wait EP
$ ls -all
total 59188
drwxrwx---+ 1 Administrators None                 0 Apr  7 23:08 .
d---rwx---+ 1 Unknown+User   Unknown+Group        0 Apr  7 23:08 ..
-rwxrwx---+ 1 Administrators None          24543042 Apr  7 23:06 1-01 Introduction.flac
-rwxrwx---+ 1 Administrators None           9792502 Apr  7 23:06 1-02 Autumn Leaves.flac
-rwxrwx---+ 1 Administrators None           6699702 Apr  7 23:06 1-03 EFX.flac
-rwxrwx---+ 1 Administrators None          11167313 Apr  7 23:07 1-04 Master Pitch.flac
-rwxrwx---+ 1 Administrators None           8094526 Apr  7 23:06 1-05 Deja Vu.flac
-rwxrwx---+ 1 Administrators None            267171 Apr  7 21:19 cover.jpg
```

Problem
=
Let's see if `ignore: .jpg` is working while I import to test:
```
user@home /cygdrive/d/download/While You Wait EP
$ beet import ./ -A
D:\download\While You Wait EP
```

Not working (<b>cover.jpg</b> is still there):
```
jj@JJ-ROOM /cygdrive/d/music/Mack 187 & Akoza/While You Wait EP
$ ls -all
total 59160
d---rwx---+ 1 jj             None        0 Apr  7 23:10 .
d---rwx---+ 1 jj             None        0 Apr  7 23:10 ..
-rwxrwx---+ 1 Administrators None 24543042 Apr  7 23:10 01-01 Introduction.flac
-rwxrwx---+ 1 Administrators None  9792502 Apr  7 23:10 01-02 Autumn Leaves.flac
-rwxrwx---+ 1 Administrators None  6699702 Apr  7 23:10 01-03 EFX.flac
-rwxrwx---+ 1 Administrators None 11167313 Apr  7 23:10 01-04 Master Pitch.flac
-rwxrwx---+ 1 Administrators None  8094526 Apr  7 23:10 01-05 Deja Vu.flac
-rwxrwx---+ 1 Administrators None   267171 Apr  7 21:19 cover.jpg
```
