### ISSUE TITLE
Convert (recently) stopped respecting paths with inline

### ISSUE THREAD

**Issue by th0rn** [sampsyo/beets#1503]
So to start off with, this used to work every time, and to the best of my memory, I haven't made any (at least related) changes to my config. It now works never, I presume because of an update, but I could be wrong.

So I have a directory with some files like:
```
/home/myuser/mymusiclibrarydir/Albumartist - Album (year) (flac)/XX. Title.flac
/home/myuser/mymusiclibrarydir/Albumartist - Album (year) (flac)/XY. Title 2.flac
```

Then I do `beet convert Albumartist - Album (year)/` (with proper escapes), and I get the prompt with all the files showing. I hit `Y`.

What I expect to happen; files to be created as follows:
```
/home/myuser/music/Albumartist - Album (year)/XX. Title.mp3
/home/myuser/music/Albumartist - Album (year)/XY. Title 2.mp3
```

What actually happens; files are created as follows:
```
/home/myuser/music/Albumartist - Album (year) (flac)/XX. Title.mp3
/home/myuser/music/Albumartist - Album (year) (flac)/XY. Title 2.mp3
```

Difference: convert doesn't use inline for path formatting (should not show flac filetype)

Replicability: always

Relevant lines from `config.yaml`:
```
paths:
    default: $albumartist - $album ($year)$format_conditional/$track. $title
item_fields:
    format_conditional: u'' if format == 'MP3' else u' (%s)' % format.lower()
plugins: chroma convert fetchart embedart lyrics lastgenre inline
convert:
    dest: /home/myuser/music/
```
