### ISSUE TITLE
plugin chroma, not found

### ISSUE THREAD

**Issue by danielfaulknor** [sampsyo/beets#1544]
My beets seems to have suddenly decided after upgrading to the latest version that the chroma plugin does not exist.

It's definitely in /usr/local/lib/python2.7/dist-packages/beetsplug

**Comment by sampsyo** [comment]
Can you please describe your setup in more detail, and provide the error message you're seeing?

**Comment by danielfaulknor** [comment]
I've installed beets via pip (pip install beets) on Ubuntu 15.04

Config:

```
directory: /music/Library
pluginpath: /usr/local/lib/python2.7/dist-packages/beetsplug
library: /music/musiclibrary.blb
import:
    move: yes
    write: yes
    resume: yes
    quiet_fallback: skip
    timid: no
    log: beetslog.txt
    art: yes
art_filename: albumart
ignore: .AppleDouble ._* *~ .DS_Store
plugins: chroma, duplicates
threaded: no
ui:
    color: yes
detail: yes
group_albums: yes
paths:
    default: $albumartist/$album/$track $title
    singleton: Singles/$artist - $title
    comp: Compilations/$album/$track $title
    albumtype:soundtrack: Soundtracks/$album/$track $title
    albumtype:ep: EPs/$albumartist - $album%aunique{} ($original_year)/$track $title
    albumtype:single: Singles/$albumartist - $album%aunique{} /$track $title
```


Error:
```
root@mediaplayer:~# beet fingerprint
** plugin chroma, not found
error: unknown command 'fingerprint'
root@mediaplayer:~#
```
