### ISSUE TITLE
(convert plugin) 'embed: yes' doesn't embed the album art

### ISSUE THREAD

**Issue by simonbcn** [sampsyo/beets#1671]
beets git version

```
....
plugins: convert replaygain lastgenre fetchart info 

fetchart:
  auto: yes
  maxwidth: 300
  cautious: yes
match:
  strong_rec_thresh: 0.30
  max_rec:
    missing_tracks: strong
    
import:
  art: yes
  languages: es en

paths:
  default: $albumartist/$album/$track - $title
  singleton: $artist - $title
  comp: Varios/$album/$track - $title

lastgenre:
  canonical: yes
   
convert:
  auto: yes
  tmpdir: /tmp
  format: mp3
  max_bitrate: 250
  embed: yes
  quiet: yes
......
```

After `beet import` an album, it downloads the album art and transcode the files but it doesn't embed the art:
```
$ beet info -i 'art' Música/Avicii/Stories/01\ -\ Waiting\ for\ Love.mp3 
art: False
```
