### ISSUE TITLE
(embedart plugin) 'remove_art_file: yes' doesn't work

### ISSUE THREAD

**Issue by simonbcn** [sampsyo/beets#1672]
beets git version
```
....
plugins: convert replaygain lastgenre fetchart info embedart

fetchart:
  auto: yes
  maxwidth: 300
  cautious: yes

embedart:
  auto: yes
  maxwidth: 300
  remove_art_file: yes

match:
  strong_rec_thresh: 0.30
  max_rec:
    missing_tracks: strong
    
import:
  art: yes
  languages: es en

paths:
  default: $albumartist/$album/$track - $title
  singleton: $artist - $title
  comp: Varios/$album/$track - $title

lastgenre:
  canonical: yes
   
convert:
  auto: yes
  tmpdir: /tmp
  command: ffmpeg -i $source -y -codec:a libmp3lame -vn -qscale:a 1 $dest
  extension: mp3
  quiet: yes
  threads: 7
  never_convert_lossy_files: yes
....
```

After `beet import` the `cover.jpg` file remains in destination folder.
