### ISSUE TITLE
ASK user when doing filesystem operations

### ISSUE THREAD

**Issue by TETYYS** [sampsyo/beets#1697]
what the actual fuck? i just imported my library explicitly stating to
```
    copy: no
    write: no
```
After importing, everything was good and not touched.
When i deleted one album and tried to `beet update` it just MOVED randomly SOME of the songs to different folders. AFAIK `move` config defaults to `no`. Program finished executing normally. I CAN'T FIND ANYTHING! My foobar2000 now just DOESN'T WORK
this shit is cataloged so fucking wrong I can't even imagine where to start imagining to start listing what's wrong with current catalog

How do I revert the change?

Those are the last lines of `beet update` :
```
Wickaman & J Malik Feat. Top Cat - Xclusive Drum & Bass - Cassanova
  albumartist: Various Artists -> Wickaman & J Malik Feat. Top Cat
  comp: True -> False
Wickaman & RV - Fabriclive 58 - Goldie - Ev's Dead
  albumartist: Various Artists -> Wickaman & RV
  comp: True -> False
Wings - Enforcers Vol. 11 & 12 - Wings
  albumartist: Various Artists -> Wings
  comp: True -> False
Wots My Code - Jungle Drum and Bass Anthems - Dubplate
  albumartist: Various Artists -> Wots My Code
  comp: True -> False
Xtrah - Fabriclive.62 - Regain Control
  albumartist: Various Artists -> Xtrah
  comp: True -> False
Xtrah & DLR - The Formula (Break Remix) / Direct Approach - Direct Approach (Remix)
  albumartist: Various Artists -> Xtrah & DLR
  comp: True -> False
Yarn & K.O. - Aphrodite presents Full Force Disc 1 - Bring Dat Beat
  albumartist: Various Artists -> Yarn & K.O.
  comp: True -> False
Yum Yum ft. Martin Greene - The Takeover Bid: Round One - Fallen Angel (Aphrodite Mix)
  albumartist: Aphrodite -> Yum Yum ft. Martin Greene
ZFE - Split - To Abandon Oneself To Despair I
  comp: False -> True
ZFE - Split - To Abandon Oneself To Despair II
  comp: False -> True
ZFE - Split - To Abandon Oneself To Despair III
  comp: False -> True
Zinc - Xclusive Drum & Bass - Steppin' Stones (Zinc & Friction Remix)
  albumartist: Various Artists -> Zinc
  comp: True -> False
Zinc Feat. Amy Bullman - Xclusive Drum & Bass - Hear No Evil (DJ Marky & Bungle Remix)
  albumartist: Various Artists -> Zinc Feat. Amy Bullman
  comp: True -> False
Zinc Feat. Slarta Jon - Xclusive Drum & Bass - Film (Zinc D'n'b Mix)
  albumartist: Various Artists -> Zinc Feat. Slarta Jon
  comp: True -> False
Zombie Flesh Eater - Amboss / Zombieflesheater - Civil War In Kingston (Version)
  comp: False -> True
Zombie Flesh Eater - Amboss / Zombieflesheater - Mindriot
  comp: False -> True
Zombie Flesh Eater - Amboss / Zombieflesheater - Tronic Dismember
  comp: False -> True
Zombie Flesh Eater - Amboss / Zombieflesheater - Antibreaks
  comp: False -> True
??????? - ??????? ?? (DJ 007 remix) - ????????? ??????? Network. ??????? ?????? -
  albumartist: Various Artists -> ??????? - ??????? ?? (DJ 007 remix)
  comp: True -> False
```

**Comment by reiv** [comment]
Damn, that sucks. For reference, could you please post your entire `config.yaml` as an attachment?

Also, when you say that only *some* songs were moved, does this mean that the others were not imported into the library (you can check by typing `beet ls artist:<ARTIST>`)?

**Comment by TETYYS** [comment]
```
directory: E:\music
library: E:\beets.yaml

plugins: discogs web missing duplicates 

art_filename: folder.jpg
fetchart: no
cautious: yes
sources: albumart *

import:
    copy: no
    write: no
```
All songs are imported.

I have the full log though, so if this doesn't have reverting capabilities I think I can move everything back to places in 4~ hours

**Comment by reiv** [comment]
I wasn't able to reproduce this bug with the config you posted, sorry. Can you make sure it's the same config used by Beets (type `beet config` and see if they match)?

**Comment by TETYYS** [comment]
```
cautious: yes
art_filename: folder.jpg
fetchart: no
library: E:\beets.yaml
sources: albumart *

plugins: discogs web missing duplicates
directory: E:\music

import:
    copy: no
    write: no
missing:
    count: no
    total: no
web:
    host: 127.0.0.1
    port: 8337
    cors: ''
duplicates:
    count: no
    full: no
    format: ''
    keys: []
    move: ''
    tag: ''
    path: no
    copy: ''
    tiebreak: {}
    album: no
    strict: no
    checksum: ''
    merge: no
    delete: no
discogs:
    tokenfile: discogs_token.json
    apikey: REDACTED
    apisecret: REDACTED
    source_weight: 0.5
```
