### ISSUE TITLE
Web plugin not showing tracks at all

### ISSUE THREAD

**Issue by ReadyP1** [sampsyo/beets#1800]
Hey there!

I've got a bit of a problem. I have beets set up to use the web plugin, but whenever I run ```beet web``` and navigate to the public IP of my EC2 instance that I have it set up on, I just get this:
![beets aren t fresh](https://cloud.githubusercontent.com/assets/6777358/12113823/5a8f7b8c-b373-11e5-87e2-a1a75ce3a852.jpg)

I have confirmed that yes, there is actual music in the music folder, and that the web plugin is enabled. If it helps, here's the ```config.yaml```:

```yaml
directory: ~/Music
library: ~/data/musiclibrary.blb
import:
    copy: no

plugins: info random web

web:
    host: 0.0.0.0
```
If you want to check out what's happening yourself, head on over [here](http://52.35.55.229:8337).
